#!/bin/bash
# =============================================================================
# Audio2Lox: Auto-generate ALSA virtual devices for all sound cards
# =============================================================================
# Scans all ALSA playback devices, detects max channel count, and generates:
#   - Individual MONO outputs for every single channel
#   - STEREO pairs for every adjacent channel pair
#   - A dmix device per card for concurrent access
#
# Usage:
#   bash generate-asound.sh              # preview to stdout
#   bash generate-asound.sh --install    # write to /etc/asound.conf
#   bash generate-asound.sh --snapclients # also create snapclient services
# =============================================================================

set -euo pipefail

INSTALL=false
SNAPCLIENTS=false
SNAPSERVER_HOST="127.0.0.1"
SNAPSERVER_PORT="1704"
OUTPUT_FILE="/etc/asound.conf"

for arg in "$@"; do
    case "$arg" in
        --install) INSTALL=true ;;
        --snapclients) SNAPCLIENTS=true; INSTALL=true ;;
    esac
done

# -----------------------------------------------------------------------------
# Detect max channels for an ALSA device
# -----------------------------------------------------------------------------
get_max_channels() {
    local device="$1"  # e.g. hw:0,0
    # Try to open with increasing channel counts
    local max=2
    for ch in 2 4 6 8; do
        if aplay -D "$device" --dump-hw-params /dev/null 2>&1 | grep -q "channels:.*$ch\|CHANNELS:.*$ch"; then
            max=$ch
        fi
    done
    # Alternative: parse hw_params directly
    local params
    params=$(aplay -D "$device" --dump-hw-params /dev/null 2>&1 || true)
    local ch_line
    ch_line=$(echo "$params" | grep -i "^CHANNELS:" | head -1 || true)
    if [ -n "$ch_line" ]; then
        # Format: CHANNELS: [2 8]  or  CHANNELS: 2
        local ch_max
        ch_max=$(echo "$ch_line" | grep -oP '\d+' | tail -1)
        if [ -n "$ch_max" ] && [ "$ch_max" -gt 0 ] 2>/dev/null; then
            max=$ch_max
        fi
    fi
    echo "$max"
}

# -----------------------------------------------------------------------------
# Parse aplay -l to get card info
# -----------------------------------------------------------------------------
declare -A CARD_NAMES
declare -A CARD_LONG_NAMES
declare -A DEVICE_NAMES

while IFS= read -r line; do
    if [[ "$line" =~ ^card\ ([0-9]+):\ ([^ ]+)\ \[([^\]]+)\].*device\ ([0-9]+):\ ([^\[]+)\[([^\]]+)\] ]]; then
        card_num="${BASH_REMATCH[1]}"
        card_id="${BASH_REMATCH[2]}"
        card_name="${BASH_REMATCH[3]}"
        dev_num="${BASH_REMATCH[4]}"
        dev_name="$(echo "${BASH_REMATCH[5]}" | xargs)"  # trim
        dev_long="${BASH_REMATCH[6]}"
        
        CARD_NAMES[$card_num]="$card_id"
        CARD_LONG_NAMES[$card_num]="$card_name"
        key="${card_num}_${dev_num}"
        DEVICE_NAMES[$key]="$dev_name"
    fi
done < <(aplay -l 2>/dev/null)

if [ ${#CARD_NAMES[@]} -eq 0 ]; then
    echo "ERROR: No ALSA playback devices found!" >&2
    exit 1
fi

# Channel name labels (for 7.1 surround default mapping)
CH_LABELS=(
    "Front-Left" "Front-Right"
    "Rear-Left" "Rear-Right"
    "Center" "LFE-Sub"
    "Side-Left" "Side-Right"
)

# -----------------------------------------------------------------------------
# Generate asound.conf
# -----------------------------------------------------------------------------
generate_config() {
    local ipc_key=1024

    cat << 'HEADER'
# =============================================================================
# Auto-generated by Audio2Lox generate-asound.sh
# =============================================================================
# DO NOT EDIT MANUALLY - re-run the generator script to update.
#
# Naming convention:
#   card<N>_ch<C>         = mono output on card N, channel C
#   card<N>_stereo<A><B>  = stereo pair on card N, channels A+B
#   card<N>_dmix          = shared mixer for card N (internal)
# =============================================================================

HEADER

    # Track all generated devices for summary
    local -a ALL_MONO=()
    local -a ALL_STEREO=()

    for card_num in $(echo "${!CARD_NAMES[@]}" | tr ' ' '\n' | sort -n); do
        card_id="${CARD_NAMES[$card_num]}"
        card_name="${CARD_LONG_NAMES[$card_num]}"
        
        # Find all devices for this card
        for key in $(echo "${!DEVICE_NAMES[@]}" | tr ' ' '\n' | sort); do
            if [[ "$key" =~ ^${card_num}_ ]]; then
                dev_num="${key#*_}"
                dev_name="${DEVICE_NAMES[$key]}"
                hw_dev="hw:${card_num},${dev_num}"
                
                # Detect max channels
                max_ch=$(get_max_channels "$hw_dev")
                
                local prefix="card${card_num}"
                if [ "$dev_num" != "0" ]; then
                    prefix="card${card_num}d${dev_num}"
                fi
                
                echo "# ==========================================================================="
                echo "# Card ${card_num}: ${card_name} - Device ${dev_num}: ${dev_name}"
                echo "# Hardware: ${hw_dev}, Max channels: ${max_ch}"
                echo "# ==========================================================================="
                echo ""

                # --- dmix ---
                echo "pcm.${prefix}_dmix {"
                echo "    type dmix"
                echo "    ipc_key ${ipc_key}"
                echo "    ipc_perm 0666"
                echo "    slave {"
                echo "        pcm \"${hw_dev}\""
                echo "        rate 48000"
                echo "        channels ${max_ch}"
                echo "        period_size 1024"
                echo "        buffer_size 4096"
                echo "    }"
                echo "}"
                echo ""
                ipc_key=$((ipc_key + 1))

                # --- Individual MONO channels ---
                for (( ch=0; ch<max_ch; ch++ )); do
                    local label=""
                    if [ $ch -lt ${#CH_LABELS[@]} ]; then
                        label="${CH_LABELS[$ch]}"
                    else
                        label="Ch${ch}"
                    fi
                    local dev_id="${prefix}_ch${ch}"
                    
                    echo "# ${dev_id}: ${card_name} → Channel ${ch} (${label})"
                    echo "pcm.${dev_id} {"
                    echo "    type route"
                    echo "    slave { pcm \"${prefix}_dmix\"; channels ${max_ch} }"
                    echo "    ttable { 0.${ch} 1.0 }"
                    echo "}"
                    echo ""
                    
                    ALL_MONO+=("${dev_id}|${card_name}|Ch${ch} ${label}|${hw_dev}")
                done

                # --- STEREO pairs ---
                for (( ch=0; ch<max_ch-1; ch+=2 )); do
                    local ch2=$((ch+1))
                    local label_l="" label_r=""
                    if [ $ch -lt ${#CH_LABELS[@]} ]; then label_l="${CH_LABELS[$ch]}"; else label_l="Ch${ch}"; fi
                    if [ $ch2 -lt ${#CH_LABELS[@]} ]; then label_r="${CH_LABELS[$ch2]}"; else label_r="Ch${ch2}"; fi
                    local dev_id="${prefix}_stereo${ch}${ch2}"
                    
                    echo "# ${dev_id}: ${card_name} → Channels ${ch}+${ch2} (${label_l} + ${label_r})"
                    echo "pcm.${dev_id} {"
                    echo "    type route"
                    echo "    slave { pcm \"${prefix}_dmix\"; channels ${max_ch} }"
                    echo "    ttable {"
                    echo "        0.${ch} 1.0"
                    echo "        1.${ch2} 1.0"
                    echo "    }"
                    echo "}"
                    echo ""
                    
                    ALL_STEREO+=("${dev_id}|${card_name}|Ch${ch}+${ch2} ${label_l}/${label_r}|${hw_dev}")
                done
            fi
        done
    done

    # Default
    echo "# ---------- Default --------------------------------------------------------"
    echo "pcm.!default {"
    echo "    type plug"
    if [ ${#ALL_STEREO[@]} -gt 0 ]; then
        local first_stereo="${ALL_STEREO[0]%%|*}"
        echo "    slave.pcm \"${first_stereo}\""
    else
        echo "    slave.pcm \"hw:0,0\""
    fi
    echo "}"
    echo ""
    echo "ctl.!default {"
    echo "    type hw"
    echo "    card 0"
    echo "}"

    # Print summary as comments
    echo ""
    echo "# ==========================================================================="
    echo "# SUMMARY OF GENERATED VIRTUAL DEVICES"
    echo "# ==========================================================================="
    echo "#"
    echo "# MONO outputs (single channel → one speaker):"
    for entry in "${ALL_MONO[@]}"; do
        IFS='|' read -r dev_id cname desc hw <<< "$entry"
        echo "#   ${dev_id}  →  ${cname} ${desc}"
    done
    echo "#"
    echo "# STEREO outputs (channel pair → two speakers):"
    for entry in "${ALL_STEREO[@]}"; do
        IFS='|' read -r dev_id cname desc hw <<< "$entry"
        echo "#   ${dev_id}  →  ${cname} ${desc}"
    done
    echo "#"
    echo "# ==========================================================================="
}

# -----------------------------------------------------------------------------
# Generate snapclient systemd services
# -----------------------------------------------------------------------------
generate_snapclients() {
    echo ""
    echo "Creating Snapclient services for all virtual devices..."
    
    # Collect all device names from the config we just wrote
    local devices=()
    devices+=($(grep -oP '^pcm\.(\w+)\s*\{' "$OUTPUT_FILE" | grep -v '_dmix' | sed 's/pcm\.//;s/ {//'))
    
    for dev_id in "${devices[@]}"; do
        local service="snapclient-${dev_id}"
        local channels=1
        # Stereo devices need -c 2
        if [[ "$dev_id" == *stereo* ]]; then
            channels=2
        fi
        
        cat > "/etc/systemd/system/${service}.service" << EOF
[Unit]
Description=Snapclient ${dev_id}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/snapclient \\
    --host ${SNAPSERVER_HOST} \\
    --port ${SNAPSERVER_PORT} \\
    --soundcard ${dev_id} \\
    --hostID ${dev_id} \\
    --player alsa \\
    --logsink system
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
        echo "  ✓ ${service}.service (ALSA: ${dev_id}, ID: ${dev_id})"
    done
    systemctl daemon-reload
    echo ""
    echo "Services created. Enable the ones you need with:"
    echo "  systemctl enable --now snapclient-<device>"
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
CONFIG=$(generate_config)

if [ "$INSTALL" = true ]; then
    if [ -f "$OUTPUT_FILE" ]; then
        cp "$OUTPUT_FILE" "${OUTPUT_FILE}.bak"
        echo "Backed up ${OUTPUT_FILE} → ${OUTPUT_FILE}.bak"
    fi
    echo "$CONFIG" > "$OUTPUT_FILE"
    echo "Written to ${OUTPUT_FILE}"
    echo ""
    # Show summary
    grep "^#   " "$OUTPUT_FILE" || true
    
    if [ "$SNAPCLIENTS" = true ]; then
        generate_snapclients
    fi
else
    echo "$CONFIG"
    echo ""
    echo "# Run with --install to write to ${OUTPUT_FILE}"
    echo "# Run with --snapclients to also create systemd services"
fi
